version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
      - ../secrets:/secrets:ro
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/secrets:ro
    env_file:
      - .env
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/secrets:ro
    env_file:
      - .env
    networks:
      - inception
    restart: always

# Déclaration des volumes liés à /home/angerard/data
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/angerard/data/wordpress
      o: bind

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/angerard/data/mariadb
      o: bind

# Réseau dédié inception (commun aux 3 services)
networks:
  inception:
    name: inception
    driver: bridge
